### ISSUE TITLE
overlap_area is not a keyword argument during overlap determination

### ISSUE THREAD

**Issue by ajulik1997** [algotom/algotom#15]
Just noticed the following comment in one of the examples that note to use overlap_area=True in the overlap determination method if there are issues with overlap determination (particularly if the sample is only partially in the outer FoVs). However, I cannot find this keyword argument in either the find_overlap or search_overlap functions.

https://github.com/algotom/algotom/blob/cb757ad702e2bb77da0be3060749c9dca8293cf3/examples/example_07_full_reconstruction_a_grid_scan_step_01.py#L159

**Comment by nghia-vo** [comment]
Thanks for pointing that out, Alex It's called **use_overlap** in the API instead. I've updated the example.

**Comment by ajulik1997** [comment]
That makes a lot of sense Nghia, thanks for that. Is there an explanation of what "use_overlap" actually does? I can see it propagates out into "__calc_overlap_metric", where it combines the ROI with some sort of weighting/ramping array if "use_overlap=True". Could you point me where in Ref (1) that is described? (I understand the linear ramp that is used for stitching once the metric is computed, but I assume this is separate from that.)

**Comment by nghia-vo** [comment]
It's a simple way to improve the robustness of calculating the correlation coefficient. 
https://github.com/algotom/algotom/blob/0198fc6066695798e4ee739aa80a0c11ab0a2739/algotom/prep/calculation.py#L448
Basically, we calculate the correlation coefficient between two regions of two images. As these two regions suppose to be the same, their combination (linear ramp or averaging) should be the same. Using this assumption we can add more factors to the calculation formula by: calculating the correlation coefficients between the first region and the combined region + the second region and the combined region. This improves the robustness of finding the overlap between images. In the paper of Algotom, this small step is not mentioned. I didn't set use_overlap =True by default due to the computational cost.

**Comment by ajulik1997** [comment]
That makes a lot of sense, thanks for that excellent description.
